apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: tasksphere-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-reader
  namespace: tasksphere-app
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-reader-binding
  namespace: tasksphere-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-reader
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: tasksphere-app
